sudo: false
language: java

jdk:
  - oraclejdk8

before_install:
  - cd WraithEngine
  
cache:
  apt: true
  directories:
    - ~/.m2

install: true
script:
  - mvn -Ddebug=true -Dorg.lwjgl.util.Debug=true -Dorg.lwjgl.util.DebugLoader=true test -B;

after_success:
  - mvn jacoco:report coveralls:report
