name: CI

on:
  push:
    paths:
      - "**.java"
      - "pom.xml"
      - ".github/**"
  pull_request:
    paths:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache maven build
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        uses: xlui/action-maven-cli/jdk8@master
        with:
          args: -B clean jacoco:prepare-agent package --file pom.xml jacoco:report sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Show Error Logs
        if: failure()
        run: |
          cat hs_err_pid*
          rm hs_err_pid*

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Generate build number
        uses: einaregilsson/build-number@v2
        with:
          token: ${{secrets.github_token}}

      - name: Print build number
        run: echo "Build number is $BUILD_NUMBER"

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache maven build
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Apply build number
        run: |
          sed -i "s|<version>dev_build</version>|<version>build_$BUILD_NUMBER</version>|g" pom.xml

      - name: Configure Maven Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: thedudefromci
        run: |

          # Create Settings file
          mkdir -p ~/.m2
          echo "<settings>" > ~/.m2/settings.xml

          # Add active profile
          echo "<activeProfiles><activeProfile>github</activeProfile></activeProfiles>" >> ~/.m2/settings.xml

          # Start repo list
          echo "<profiles><profile><id>github</id><repositories>" >> ~/.m2/settings.xml

          # Add Maven Central repo
          echo "<repository><id>central</id><url>https://repo1.maven.org/maven2</url><releases><enabled>true</enabled></releases><snapshots><enabled>false</enabled></snapshots></repository>" >> ~/.m2/settings.xml

          # Add WraithEngine repo
          echo "<repository><id>github</id><name>GitHub thedudefromci Apache Maven Packages</name><url>https://maven.pkg.github.com/thedudefromci/WraithEngine</url></repository>" >> ~/.m2/settings.xml

          # End repo list
          echo "</repositories></profile></profiles>" >> ~/.m2/settings.xml

          # Add authentication
          echo "<servers><server><id>github</id><username>${USERNAME}</username><password>${GITHUB_TOKEN}</password></server></servers>" >> ~/.m2/settings.xml

          # Finish settings file
          echo "</settings>" >> ~/.m2/settings.xml

          # Trigger deploy
          mvn -B deploy
