name: CI

on:
  push:
    paths:
      - "**.java"
      - "pom.xml"
      - "**/pom.xml"
      - ".github/**"
  pull_request:
    paths:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache maven build
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Copy Maven settings.xml
        run: |
          mkdir -p ~/.m2
          sed "s/GITHUB_REPO_ACCESS/${GITHUB_REPO_ACCESS}/" .github/workflows/settings.xml > ~/.m2/settings.xml
        env:
          GITHUB_REPO_ACCESS: ${{ secrets.GITHUB_REPO_ACCESS }}

      - name: Build with Maven
        uses: xlui/action-maven-cli/jdk8@master
        with:
          args: -B clean jacoco:prepare-agent package --file pom.xml jacoco:report sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Show Error Logs
        if: failure()
        run: |
          cat hs_err_pid* 2> /dev/null || true
          rm hs_err_pid* 2> /dev/null || true

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Generate build number
        uses: einaregilsson/build-number@v2
        with:
          token: ${{secrets.github_token}}

      - name: Print build number
        run: echo "Build number is $BUILD_NUMBER"

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache maven build
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Apply build number
        run: |
          sed -i "s|<version>dev_build</version>|<version>build_$BUILD_NUMBER</version>|g" pom.xml
          sed -i "s|<version>dev_build</version>|<version>build_$BUILD_NUMBER</version>|g" Awgen-Client/pom.xml
          sed -i "s|<version>dev_build</version>|<version>build_$BUILD_NUMBER</version>|g" Awgen-Lib/pom.xml
          sed -i "s|<version>dev_build</version>|<version>build_$BUILD_NUMBER</version>|g" Awgen-Server/pom.xml

      - name: Copy Maven settings.xml
        run: |
          mkdir -p ~/.m2
          sed "s/GITHUB_REPO_ACCESS/${GITHUB_REPO_ACCESS}/" .github/workflows/settings.xml > ~/.m2/settings.xml
        env:
          GITHUB_REPO_ACCESS: ${{ secrets.GITHUB_REPO_ACCESS }}

      - name: Maven Deploy
        run: |
          mvn -B deploy
